### PR TITLE
Added SWISH to PaymentMethodType

### PR DESCRIPTION
**Pull request by Sebbe**
This closes issue #99

### CODE REVIEW

**Comment by Sebbe** [comment]
I will be honest and say that I haven't tested this. But based on the error message I will say this should fix the issue we have.

**Comment by frederikvig** [comment]
Thanks @Sebbe. Will include this with the next release.

**Comment by Sebbe** [comment]
Thanks @frederikvig 
When will next release be?

**Comment by frederikvig** [comment]
@Sebbe Plan is September, unfortunately no exact date yet.

**Comment by frederikvig** [comment]
I created a new release (3.5.4) for it now and uploaded it to https://nuget.optimizely.com/. They usually approve the packages within 24 hours.

**Pull request merged**
